export const Package = [
  {
    Name: "Mini Pack",
    Img: "./img/p-1.png",
    Pair: 100,
    Color: "All",
    Size: "All",
    Delivery: "3d",
    Shipping: 100,
    ItemsPrice: 45,
    Price: 4600,
  },
  {
    Name: "Medium Pack",
    Img: "./img/p-2.png",
    Pair: 300,
    Color: "All",
    Size: "All",
    Delivery: "7d",
    Shipping: 0,
    ItemsPrice: 45,
    Price: 13500,
  },
  {
    Name: "Large Pack",
    Img: "./img/p-3.png",
    Pair: 500,
    Color: "All",
    Size: "All",
    Delivery: "10d",
    Shipping: 0,
    ItemsPrice: 45,
    Price: 22500,
  },
];
